baseURL = "https://romaisablbgn.github.io/"
languageCode = "en-us"
title = "romaisa"
copyright = "© 2026 Romaisa Balabagan"

mainSections = ["posts"]

[params]
  description = "A personal blog about programming, AI, data analysis, and the messy process of learning Data Science."
  colorScheme = "toggle"
  disableFontPreload = true

[params.author]
  name = "Romaisa Balabagan"

[[params.links]]
  name = "GitHub"
  url = "https://github.com/romaisablbgn"

[[params.links]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/romaisablbgn"

[[params.links]]
  name = "Instagram"
  url = "https://instagram.com/romaisablbgn"
